// Stage: emit. Joins decisions, the case corpus, and the two similarity
// tables into the versioned SeedBundle the web app loads. Refuses to emit a
// bundle that violates the domain contracts.
import type { Case, Decision, SeedBundle } from '@ppi/domain';
import { validateSeedBundle } from '@ppi/domain';
import type { CorpusCase } from '../corpus.js';
import type { SimilarityTable } from '../tables.js';

/** Bumped whenever emitted content changes shape or meaning — the IndexedDB adapter reseeds on mismatch. */
export const SEED_VERSION = 'seed-v1.1-pipeline-tables';

export function assembleBundle(
  decisions: Decision[],
  cases: CorpusCase[],
  caseTable: SimilarityTable,
  siblingTable: SimilarityTable,
  seedVersion: string = SEED_VERSION,
): SeedBundle {
  const caseById = new Map(cases.map((c) => [c.id, c]));

  const withEvidence = decisions.map((d): Decision => {
    const ranked = caseTable.rows[d.id] ?? [];
    const evidenceCases = ranked.map(({ id, score }): Case => {
      const c = caseById.get(id);
      if (!c) throw new Error(`decision ${d.id}: ranked case ${id} not in the corpus`);
      // patternIndex points into THIS decision's patterns array, so it only
      // survives for cases extracted from this decision's own evidence.
      const ownPatternIndex = c.origin?.decisionId === d.id ? c.origin.patternIndex : undefined;
      return {
        event: c.event,
        when: c.when,
        similarity: score,
        outcome: c.outcome,
        ...(ownPatternIndex !== undefined ? { patternIndex: ownPatternIndex } : {}),
        detail: c.detail,
        tags: c.tags,
      };
    });
    return { ...d, evidence: { ...d.evidence, cases: evidenceCases, precedents: [] } };
  });

  const siblings: SeedBundle['siblings'] = {};
  for (const [id, scored] of Object.entries(siblingTable.rows)) {
    if (scored.length > 0) siblings[id] = scored.map((s) => s.id);
  }

  const bundle: SeedBundle = { seedVersion, decisions: withEvidence, siblings };
  const violations = validateSeedBundle(bundle);
  if (violations.length > 0) {
    throw new Error(`refusing to emit a seed bundle that violates the domain contracts:\n${violations.join('\n')}`);
  }
  return bundle;
}

export function renderSeedTs(bundle: SeedBundle): string {
  return `// GENERATED by @ppi/pipeline (emit stage) — do not edit by hand.
// Inputs and tables live in packages/pipeline/data/; regenerate with
// \`npm run -w @ppi/pipeline embed && npm run -w @ppi/pipeline emit\`.
import type { SeedBundle } from '@ppi/domain';

export const SEED = ${JSON.stringify(bundle, null, 2)} satisfies SeedBundle;
`;
}
